### ISSUE TITLE
MelissaNet and other libraries could not be found

### ISSUE THREAD

**Issue by Maahdima** [MythicalCuddles/DiscordBot#8]
Hi and thanks for sharing this amazing project 
I wanna use your project for mine and to learn from it to create my own discord bot but it has lots of errors in reading and using libraries, i.e I cant find mellisa net library in c# libraries!
Now i was wondering could you please help me to run this project and use it for my own project?!

**Comment by MythicalCuddles** [comment]
Hi, thanks for your interest!

Unfortunately, MelissaNet is a private respiratory at the moment as it is no longer worked on. However, it should come packed in the [release download](https://github.com/MythicalCuddles/DiscordBot/releases/tag/v3.2.0) which you should be able to add to your references directly from there, and any other libraries that you may be missing. (You're looking for the file called DiscordBot-Release-3.2.0-WIN.zip in the Assets at the bottom of the page) Hope this helps 😄

**Comment by Maahdima** [comment]
Ok btw thanks a lot, you saved my life!
It will realy helped out of me
Im gonna work on it and use your amazing codings for my project if its allowed :)

**Comment by MythicalCuddles** [comment]
Glad to help, if you do end up using the project, please do keep in mind the license I have on it, thanks!
I hope my code is able to assist you in your learnings for your own projects and hope you can understand it enough to give coding it yourself a go! Good luck 😄
