### ISSUE TITLE
Bot restarts in a time.

### ISSUE THREAD

**Issue by Maahdima** [MythicalCuddles/DiscordBot#9]
Hello and greetings again!
Im working on your codes for a test bot, but now i find out that it restarts after a time repeatedly and i dont know why?!!
when Im going to check bots uptime via command it writes just hours, although it turned on for days.
I wanna know have you ever face with it? If so, you think is it a coding problem or discord rules and whats your suggestion to fix it?
Thanks a lot.

**Comment by MythicalCuddles** [comment]
Hi!

I had encountered something on the lines of what you're describing when developing the bot myself but could never figure out why it was the case.

I'd recommend turning on debug logging (set LogLevel to LogSeverity.Debug) to see if you could spot anything in there, or looking into the exception that is thrown when the Disconnected event is triggered, which should run when the bot goes offline. The event has an exception attached to it, so you should just be able to output it directly. You will, however, need to either output this to a file or alternatively turn off DefaultRetryMode to prevent the bot from auto restarting and clearing it from the console. 

For me, when I did this, I found for me that there was an issue relating to sockets, but it happened so rarely that I could never test anything to fix it.

Sorry, I can't provide a working solution, but I hope this helps :)

**Comment by Maahdima** [comment]
Hello!
Now Im going to test and see what happens, and also trying to fix this problem with your descriptions.
Really thanks for your advices. It should help me a lot.
At last I wanna say that it means a lot to me! :)
